### ISSUE TITLE
problem with cache for same API URL with different parameters

### ISSUE THREAD

**Issue by marijana** [alecritson/Placid#18]
This is my code:
`{% set options = {method : 'POST'} %}`
`{% set requesten = craft.placid.request('LangEn', options) %}`
`{% set requestde = craft.placid.request('LangDe', options) %}`

These requests have same API URL but different language parameter set in query parameters.

When I turn on caching for both requests, they both return value from first request.
When caching is off, then they return different values.

Setting all parameters either in template or in plugin admin area results in same behaviour.

I am on Placid 1.6.6 and Craft Pro 2.4.2726

Btw, thanks for a great plugin!

**Comment by alecritson** [comment]
Hey @marijana 

I managed to figure out what was going wrong, it was due to it being a `POST` request, Placid would append the query string but because with a `POST` request you are sending form data, so it doesn't show up! An oversight on my part. 

If you download version [`1.6.16`](https://github.com/alecritson/Placid/releases/tag/1.6.16) it should be fixed  :) 

Any trouble just let me know, and thanks for the feedback :+1:

**Comment by marijana** [comment]
Yes, its working now. 
Thnx a lot!
